#!/usr/bin/env python3
"""Inject SEO tags into expo web export + write robots.txt/sitemap.xml.

Usage: python3 scripts/inject-web-seo.py dist/ https://bendcalc.wattflow.net [--ga4-id G-XXXX]

The GA4 measurement ID can also come from the GA4_ID env var. When no ID is
given, no GA4 code is emitted (pages stay analytics-free). The ID is never
hardcoded; it is injected at build time only.
Replaces the old /tmp/seo-inject.py (deleted during /tmp cleanup 2026-09-29).
"""
import html
import os
import re
import sys

EXPORT_DIR = sys.argv[1].rstrip("/")
BASE_URL = sys.argv[2].rstrip("/")

GA4_TEMPLATE = """<script async src="https://www.googletagmanager.com/gtag/js?id={gid}"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){{dataLayer.push(arguments);}}
gtag('js', new Date());
gtag('config', '{gid}');
</script>"""


def resolve_ga4_id(argv: list) -> str | None:
    for i, a in enumerate(argv):
        if a == "--ga4-id" and i + 1 < len(argv):
            candidate = argv[i + 1].strip()
            break
    else:
        candidate = (os.environ.get("GA4_ID") or "").strip()
    if candidate and re.fullmatch(r"G-[A-Z0-9]{4,}", candidate):
        return candidate
    if candidate:
        print(f"warning: ignoring malformed GA4 ID {candidate!r}", file=sys.stderr)
    return None


GA4_ID = resolve_ga4_id(sys.argv)
GA4_SNIPPET = GA4_TEMPLATE.format(gid=html.escape(GA4_ID)) if GA4_ID else ""

TITLE = "Conduit Bend Calc \u2014 Free Conduit Bending Calculator (Offset, Stub, Saddles)"
DESC = (
    "Free conduit bending calculator for electricians: offset bends, 90\u00b0 stubs, "
    "3-point and 4-point saddles, rolling offsets and kicked 90s. Mark spacing, "
    "shrink and take-up in inches or metric. Get Conduit Bend Calc Pro on Google "
    "Play to calibrate measurements to your actual bender."
)
KEYWORDS = (
    "conduit bending calculator, offset bend calculator, stub up calculator, "
    "3 point saddle calculator, 4 point saddle calculator, rolling offset "
    "calculator, electrician bender app, EMT bending"
)

SEO_BLOCK = f"""<title>{html.escape(TITLE)}</title>
<meta name="description" content="{html.escape(DESC)}" />
<meta name="keywords" content="{html.escape(KEYWORDS)}" />
<link rel="canonical" href="{BASE_URL}/" />
<meta property="og:type" content="website" />
<meta property="og:site_name" content="Conduit Bend Calc" />
<meta property="og:title" content="{html.escape(TITLE)}" />
<meta property="og:description" content="{html.escape(DESC)}" />
<meta property="og:url" content="{BASE_URL}/" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:title" content="{html.escape(TITLE)}" />
<meta name="twitter:description" content="{html.escape(DESC)}" />
"""

index_path = f"{EXPORT_DIR}/index.html"
with open(index_path) as f:
    content = f.read()

# Remove any existing <title> to avoid duplicates, then inject before </head>.
content = re.sub(r"<title>.*?</title>", "", content, flags=re.DOTALL)
content = content.replace("</head>", SEO_BLOCK + "</head>", 1)
if GA4_SNIPPET:
    content = content.replace("</head>", GA4_SNIPPET + "</head>", 1)

with open(index_path, "w") as f:
    f.write(content)

# 隐私页（若已拷贝到 dist）：同样注入 GA4 基础代码，保证整站口径一致。
privacy_path = f"{EXPORT_DIR}/privacy.html"
if GA4_SNIPPET and os.path.exists(privacy_path):
    with open(privacy_path) as f:
        privacy = f.read()
    if "googletagmanager" not in privacy:
        privacy = privacy.replace("</head>", GA4_SNIPPET + "</head>", 1)
        with open(privacy_path, "w") as f:
            f.write(privacy)
        print("GA4 injected into privacy.html")

# 4 个 SPA 工具页 shell（scripts/gen-seo-tool-shells.ts 生成 dist/<slug>/index.html）。
# 若 shell 在 GA4 注入之后生成（见 CHANGELOG 构建顺序），它们已经继承了 index.html
# 的 gtag；若在其之前生成，则此处补齐，保证新工具页无论构建顺序都能被 GA4 覆盖。
TOOL_SHELL_SLUGS = ["offset", "4-point-saddle", "shrink", "stub-up"]
if GA4_SNIPPET:
    for slug in TOOL_SHELL_SLUGS:
        shell_path = f"{EXPORT_DIR}/{slug}/index.html"
        if not os.path.exists(shell_path):
            continue
        with open(shell_path) as f:
            shell = f.read()
        if "googletagmanager" in shell:
            continue
        shell = shell.replace("</head>", GA4_SNIPPET + "</head>", 1)
        with open(shell_path, "w") as f:
            f.write(shell)
        print(f"GA4 injected into {slug}/index.html")

with open(f"{EXPORT_DIR}/robots.txt", "w") as f:
    f.write(f"User-agent: *\nAllow: /\n\nSitemap: {BASE_URL}/sitemap.xml\n")

# Standalone SEO landing pages generated by scripts/gen-seo-pages.py
# (dist/<slug>/index.html). Keep in sync with that script's page list.
SEO_PATHS = [
    "conduit-bending-calculator/",
    "offset-calculator/",
    "rolling-offset-calculator/",
    "stub-up-calculator/",
    "3-point-saddle-calculator/",
    "4-point-saddle-calculator/",
    # Batch 2 (2026-09-29). Keep in sync with scripts/gen-seo-pages.py page list.
    "kick-90-calculator/",
    "90-degree-bend-calculator/",
    "conduit-bending-chart/",
    "conduit-shrink-calculator/",
    "parallel-offset-calculator/",
    "how-to-bend-emt-conduit/",
    # Batch 4 (2026-10-04, P0 interactive tools). Generated as SPA shells by
    # scripts/gen-seo-tool-shells.ts (not content pages by gen-seo-pages.py),
    # but they share the same sitemap. Keep in sync with src/seo/toolPages.ts.
    "offset/",
    "4-point-saddle/",
    "shrink/",
    "stub-up/",
    # Batch 3 (2026-09-29). Keep in sync with scripts/gen-seo-pages.py page list.
    "conduit-bending-formula/",
    "hand-bender-markings/",
    "emt-sizes-chart/",
    "box-offset-bend/",
    "how-to-bend-3-4-emt/",
    "emt-vs-rigid-bending/",
]

with open(f"{EXPORT_DIR}/sitemap.xml", "w") as f:
    f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
    f.write('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n')
    f.write(
        "  <url>\n"
        f"    <loc>{BASE_URL}/</loc>\n"
        "    <changefreq>weekly</changefreq>\n"
        "    <priority>1.0</priority>\n"
        "  </url>\n"
    )
    for path in SEO_PATHS:
        f.write(
            "  <url>\n"
            f"    <loc>{BASE_URL}/{path}</loc>\n"
            "    <changefreq>monthly</changefreq>\n"
            "    <priority>0.8</priority>\n"
            "  </url>\n"
        )
    f.write("</urlset>\n")

print(f"SEO injected: title={TITLE[:40]}... base={BASE_URL}")
print(f"GA4: {'on (' + GA4_ID + ')' if GA4_ID else 'off'}")


# ---------------------------------------------------------------------------
# Service worker: 预缓存只放首屏关键资源（HTML shell + index.html 直接引用的
# entry bundle）；按路由拆分的 async chunk（工具页 / 内部 App）不预缓存，
# 但首次在线加载时按需写入 runtime cache，之后离线也能用。
# 不缓存任何第三方（gtag 等）或图片，避免无谓占用。
# ---------------------------------------------------------------------------
html_path = f"{EXPORT_DIR}/index.html"
with open(html_path) as f:
    index_html = f.read()
entry_match = re.search(r'src="(/_expo/static/js/web/[^"]+\.js)"', index_html)
precache = ["/", "/index.html"]
if entry_match:
    precache.append(entry_match.group(1))
version = (
    os.path.basename(entry_match.group(1)).split(".")[0]
    if entry_match
    else "v1"
)
sw = f"""/* Generated by scripts/inject-web-seo.py. Do not edit in dist. */
const CACHE = 'bendcalc-shell-{version}';
const PRECACHE = {precache!r};

self.addEventListener('install', (event) => {{
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting()),
  );
}});

self.addEventListener('activate', (event) => {{
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))),
      )
      .then(() => self.clients.claim()),
  );
}});

/** 只对同源 JS chunk 做 cache-first（命中就返回，未命中回源并回填）。 */
async function cachedScript(request) {{
  const cache = await caches.open(CACHE);
  const hit = await cache.match(request);
  if (hit) return hit;
  const response = await fetch(request);
  if (response.ok) {{
    cache.put(request, response.clone());
  }}
  return response;
}}

self.addEventListener('fetch', (event) => {{
  const {{ request }} = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // 导航：优先网络，离线回退缓存的 SPA shell（SPA 路由自己解析 path）。
  if (request.mode === 'navigate') {{
    event.respondWith(fetch(request).catch(() => caches.match('/index.html')));
    return;
  }}

  // 首屏关键资源 + 按路由拆分的 JS chunk：cache-first。
  if (
    PRECACHE.includes(url.pathname) ||
    url.pathname.startsWith('/_expo/static/js/web/')
  ) {{
    event.respondWith(cachedScript(request));
  }}
}});
"""
with open(f"{EXPORT_DIR}/sw.js", "w") as f:
    f.write(sw)
print(
    f"Service worker wrote: cache={version}, precache={precache}"
)
